Pojisteni/Pojisteni/Models/Insured.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Pojisteni.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;

namespace Pojisteni.Models
{
    public class Insured
    {
        [Key]
        public int ID { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [Display(Name="Jméno")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [Display(Name = "Příjmení")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Povinné pole")]
        [EmailAddress(ErrorMessage = "Neplatná emailová adresa")]
        [Display(Name = "E-Mail")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [StringLength(9, MinimumLength = 9, ErrorMessage = "{0} musí mít {1} čísel (bez mezer a bez předvolby)")]
        [Display(Name = "Mobil")]
        public string PhoneNumber { get; set; }


        [StringLength(10, ErrorMessage = "{0} musí mít délku alespoň {2} a nejvíc {1} čísel.", MinimumLength = 9)]
        [Required(ErrorMessage = "Vypňte rodné číslo")]
        [Display(Name = "Rodné číslo")]
        public string IdentityNumber { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [Display(Name = "Adresa")]
        public string Adress { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [Display(Name = "Město")]
        public string City { get; set; }


        [Required(ErrorMessage = "Povinné pole")]
        [StringLength(5,MinimumLength = 5, ErrorMessage = "{0} musí mít {1} čísel")]
        [Display(Name = "PSČ")]
        public string PostalCode { get; set; }

        public virtual ICollection<InsuranceInsured>? InsuranceInsureds { get; set; }

        [Display(Name = "Příjmení a jméno")]
        public virtual string LastNameAndName => $"{LastName} {Name}";

        [Display(Name = "Adresa")]
        public virtual string FullAdress => $"{Adress}, {City}";
    }
}

Pojisteni/Pojisteni/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pojisteni.Data;
using Pojisteni.Models;

namespace Pojisteni.Controllers
{
    [Authorize(Roles = "admin,insured")]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AccountIdentity> _userManager;

        public EventsController(ApplicationDbContext context, UserManager<AccountIdentity> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            if(User.IsInRole("admin"))
            {
                var applicationDbContext = _context.Event.Include(i => i.InsuranceInsured).ThenInclude(i => i.Insurance).Include(i => i.InsuranceInsured).ThenInclude(i => i.Insured);
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var user = await _userManager.GetUserAsync(User);
                var applicationDbContext = _context.Event.Where(m => m.InsuranceInsured.Insured.ID == user.InsuredID).Include(i => i.InsuranceInsured).ThenInclude(i => i.Insurance).Include(i => i.InsuranceInsured).ThenInclude(i => i.Insured);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);

            var @event = await _context.Event
                .Include(m => m.InsuranceInsured)
                .ThenInclude(m => m.Insurance)
                .ThenInclude(m => m.InsuranceInsureds)
                .ThenInclude(m => m.Insured)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (@event == null)
            {
                return NotFound();
            }


            if(!User.IsInRole("admin") && @event.InsuranceInsured.Insured.ID != user.InsuredID)
            {
                return RedirectToAction("Error" , "Error" , new { code = 401 });
            }

            return View(@event);
        }

        // GET: Events/Create
        public async Task<IActionResult> Create(int? insuranceInsuredID)
        {
            if (insuranceInsuredID == null)
            {
                return NotFound();
            }

            if (!await _context.InsuranceInsured.AnyAsync(m => m.ID == insuranceInsuredID))
            {
                return NotFound();
            }

            var InsuranceInsured = await _context.InsuranceInsured.FirstOrDefaultAsync(m => m.ID == insuranceInsuredID);

            if (InsuranceInsured.Status)
            {
                return RedirectToAction("Error", "Error", new { text = "K neaktivní pojistce nelze vložit pojistnou událost !" });
            }

            ViewData["InsuranceInsured"] = InsuranceInsured;
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,InsuranceInsuredID,Description, DateTime, InsertDateTime, Settled")] Event @event, int insuranceInsuredID)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                var insured = await _context.InsuranceInsured.Where(m => m.ID == insuranceInsuredID).Include(m => m.Insured).Select(m => m.Insured.ID).FirstOrDefaultAsync();
                return RedirectToAction("Details" , "Insureds" , new { id = insured });
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,InsuranceInsuredID,Description, DateTime, InsertDateTime, Settled")] Event @event)
        {
            if (id != @event.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(m => m.InsuranceInsured)
                .ThenInclude(m => m.Insurance)
                .ThenInclude(m => m.InsuranceInsureds)
                .ThenInclude(m => m.Insured)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Event == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Event'  is null.");
            }
            var @event = await _context.Event.FindAsync(id);
            if (@event != null)
            {
                _context.Event.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Event?.Any(e => e.ID == id)).GetValueOrDefault();
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> SetDone(int id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }
            if (!EventExists(id))
            {
                return RedirectToAction("Error", "Error", new { text = "Pojistná událost neexistuje !" });
            }

            var @event = await _context.Event.FindAsync(id);
            @event.Settled = true;
            _context.Update(@event);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Pojisteni/Pojisteni/Controllers/InsuranceInsuredsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pojisteni.Data;
using Pojisteni.Models;

namespace Pojisteni.Controllers
{
    [Authorize(Roles = "admin")]
    public class InsuranceInsuredsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InsuranceInsuredsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InsuranceInsureds
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.InsuranceInsured.Include(i => i.Insurance).Include(i => i.Insured);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: InsuranceInsureds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.InsuranceInsured == null)
            {
                return NotFound();
            }

            var insuranceInsured = await _context.InsuranceInsured
                .Include(i => i.Insurance)
                .Include(i => i.Insured)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (insuranceInsured == null)
            {
                return NotFound();
            }

            return View(insuranceInsured);
        }

        // GET: InsuranceInsureds/Create
        public async Task<IActionResult> Create(int? insuredID)
        {
            if(insuredID == null)
            {
                return NotFound();
            }

            if(!await _context.Insurance.AnyAsync())
            {
                return RedirectToAction("Error", "Error", new { text = "Nemáte založené žádné pojištění" });
            }

            ViewData["InsuranceID"] = new SelectList(_context.Insurance, "ID", "Name");
            ViewData["Insured"] = await _context.Insured.FirstOrDefaultAsync(m => m.ID == insuredID);
            return View();
        }

        // POST: InsuranceInsureds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InsuredID,InsuranceID,Amount,Subject,StartsAt,EndsAt")] InsuranceInsured insuranceInsured, int insuredID)
        {
            if (ModelState.IsValid)
            {
                _context.Add(insuranceInsured);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(InsuredsController.Details), "Insureds", new {id = insuranceInsured.InsuredID });
            }
            ViewData["InsuranceID"] = new SelectList(_context.Insurance, "ID", "Name", insuranceInsured.InsuranceID);
            ViewData["Insured"] = await _context.Insured.FirstOrDefaultAsync(m => m.ID == insuredID);
            return View(insuranceInsured);
        }

        // GET: InsuranceInsureds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.InsuranceInsured == null)
            {
                return NotFound();
            }

            var insuranceInsured = await _context.InsuranceInsured
                .Include(i => i.Insurance)
                .Include(i => i.Insured)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (insuranceInsured == null)
            {
                return NotFound();
            }
            ViewData["InsuranceID"] = new SelectList(_context.Insurance, "ID", "Name", insuranceInsured.InsuranceID);
            ViewData["Insured"] = insuranceInsured.Insured;
            return View(insuranceInsured);
        }

        // POST: InsuranceInsureds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,InsuredID,InsuranceID,Amount,Subject,StartsAt,EndsAt")] InsuranceInsured insuranceInsured)
        {
            if (id != insuranceInsured.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(insuranceInsured);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InsuranceInsuredExists(insuranceInsured.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(InsuredsController.Details), "Insureds", new { id = insuranceInsured.InsuredID });
            }

            ViewData["InsuranceID"] = new SelectList(_context.Insurance, "ID", "Name", insuranceInsured.InsuranceID);
            ViewData["Insured"] = await _context.Insured.FirstOrDefaultAsync(m => m.ID == insuranceInsured.InsuredID);
            
            return View(insuranceInsured);
        }

        // GET: InsuranceInsureds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.InsuranceInsured == null)
            {
                return NotFound();
            }

            var insuranceInsured = await _context.InsuranceInsured
                .Include(i => i.Insurance)
                .Include(i => i.Insured)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (insuranceInsured == null)
            {
                return NotFound();
            }

            return View(insuranceInsured);
        }

        // POST: InsuranceInsureds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.InsuranceInsured == null)
            {
                return Problem("Entity set 'ApplicationDbContext.InsuranceInsured'  is null.");
            }
            var insuranceInsured = await _context.InsuranceInsured.FindAsync(id);
            if (insuranceInsured != null)
            {
                _context.InsuranceInsured.Remove(insuranceInsured);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(InsuredsController.Details), "Insureds", new { id = insuranceInsured.InsuredID });
        }

        private bool InsuranceInsuredExists(int id)
        {
          return (_context.InsuranceInsured?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Pojisteni/Pojisteni/Views/Insureds/Create.cshtml
@model Pojisteni.Models.Insured

@{
    ViewData["Title"] = "Nový pojištěnec";
}
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">

        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="Name" class="control-label"></label>
                <div class="position-relative">
                    <input asp-for="Name" class="form-control" id="first-name-icon" required />
                    <div class="form-control-icon">
                        <i data-feather="user"></i>
                    </div>
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="LastName" class="control-label"></label>
                <div class="position-relative">
                    <input asp-for="LastName" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="user"></i>
                    </div>
                </div>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="Email" class="control-label"></label>
                <div class="position-relative">
                    <input asp-for="Email" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="mail"></i>
                    </div>
                </div>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <div class="position-relative">
                    <input type="number" asp-for="PhoneNumber" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="phone"></i>
                    </div>
                </div>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="IdentityNumber" class="control-label"></label>
                <div class="position-relative">
                    <input type="number" asp-for="IdentityNumber" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="info"></i>
                    </div>
                </div>
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="Adress" class="control-label"></label>
                <div class="position-relative">
                    <input asp-for="Adress" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="home"></i>
                    </div>
                </div>
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="City" class="control-label"></label>
                <div class="position-relative">
                    <input asp-for="City" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="map"></i>
                    </div>
                </div>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="form-group has-icon-left">
                <label asp-for="PostalCode" class="control-label"></label>
                <div class="position-relative">
                    <input type="number" asp-for="PostalCode" class="form-control" required />
                    <div class="form-control-icon">
                        <i data-feather="tag"></i>
                    </div>
                </div>
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 d-flex justify-content-start">
            <button type="submit" class="btn btn-primary mr-1 mb-1">Uložit</button>
        </div>
    </div>
</form>

Pojisteni/Pojisteni/Views/Insureds/Delete.cshtml
@model Pojisteni.Models.Insured

@{
    ViewData["Title"] = "Smazat pojištěnce";
}
<h4>@ViewData["Title"] @Html.DisplayFor(model => model.LastNameAndName) ?</h4>
<hr />
<div class="row mb-2">
    <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
        @Html.DisplayNameFor(model => model.LastNameAndName)
    </div>
    <div class="col">
        @Html.DisplayFor(model => model.LastNameAndName)
    </div>
</div>

<div class="row mb-2">
    <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
        @Html.DisplayNameFor(model => model.IdentityNumber)
    </div>
    <div class="col">
        @Html.DisplayFor(model => model.IdentityNumber)
    </div>
</div>

<form asp-action="Delete">
    <input type="hidden" asp-for="ID" />
    <input type="submit" value="ANO" class="btn btn-danger" />
    <a href="javascript:history.back()" class="btn btn-warning">NE</a>
</form>

Pojisteni/Pojisteni/Views/Insureds/Details.cshtml
@model Pojisteni.Models.Insured

@{
    ViewData["Title"] = "Detail pojištěnce";
}
<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-sm-6 col-md-4 col-xl-3 my-3">
            <img src="~/img/user.png" alt="avatar" class="img-fluid avatar avatar-status h-75" />
        </div>
        <div class="col-sm-6 px-3 my-3">
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.LastNameAndName)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.LastNameAndName)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.IdentityNumber)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.IdentityNumber)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.Adress)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.Adress)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.City)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.City)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.PostalCode)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.PostalCode)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.Email)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.Email)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </div>
                <div class="col">
                    @Html.DisplayFor(model => model.PhoneNumber)
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-3 col-md-3 col-xl-2 font-bold">
                    Login
                </div>
                <div class="col">
                    @(ViewBag.HasLogin ? "ANO" : "NE")
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <p>
            <a asp-action="RegisterInsured" asp-controller="Account" asp-route-insuredid="@Model.ID" class="btn btn-secondary @(ViewBag.HasLogin ? "disabled" : "")">Založit login</a>
            <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-warning">Editovat</a>
            <a asp-action="Delete" asp-route-id="@Model.ID" class="btn btn-danger">Odstranit</a>
        </p>
    </div>
    <hr />
    <div class="row">
        <p>
            <a asp-action="Create" asp-controller="InsuranceInsureds" asp-route-insuredid="@Model.ID" class="btn btn-primary @(ViewBag.InsuranceCount > 0 ? "" : "disabled")">Nové pojištění</a>
        </p>
    </div>
    <div class="row mb-3">
        @if (Model.InsuranceInsureds.Count() > 0)
        {
            <table class="table table-sm table-bordered table-responsive">
                <thead>
                    <tr>
                        <th>
                            Název
                        </th>
                        <th>
                            Částka
                        </th>
                        <th class="text-center">
                            Status
                        </th>
                        <th class="fit"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.InsuranceInsureds)
                    {
                        <tr>
                            <td class="align-middle">
                                <a asp-action="Details" asp-controller="InsuranceInsureds" asp-route-id="@item.ID">@Html.DisplayFor(modelItem => item.Insurance.Name)</a>
                            </td>
                            <td class="align-middle">
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td class="align-middle text-center">
                                @if (item.Status)
                                {
                                    <span class="badge bg-danger">@item.StatusString</span>
                                }
                                else
                                {
                                    <span class="badge bg-success">@item.StatusString</span>
                                }
                            </td>
                            <td class="align-middle fit">
                                <a asp-action="Create" asp-controller="Events" asp-route-insuranceinsuredid="@item.ID" class="btn btn-secondary @(item.Status ? "disabled" : "")">Nahlásit pojistnou událost</a>
                                <a asp-action="Edit" asp-controller="InsuranceInsureds" asp-route-id="@item.ID" class="btn btn-warning">Editovat</a>
                                <a asp-action="Delete" asp-controller="InsuranceInsureds" asp-route-id="@item.ID" class="btn btn-danger">Odstranit</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="container-fluid">
                <div class="alert alert-light-warning text-center h6" role="alert">
                    Pojištěnec zatím nemá sjednané žádná pojištění
                </div>
            </div>
        }
    </div>
</div>

Pojisteni/Pojisteni/Views/Insureds/Index.cshtml
@model IEnumerable<Pojisteni.Models.Insured>

@{
    ViewData["Title"] = "Pojištěnci";
}
<p>
    <a asp-action="Create" class="btn btn-primary"><i data-feather="plus-circle" class="mr-2"></i>Nový pojištenec</a>
</p>
@if (Model.Count() > 0)
{

    <table id="data-table" class="table table-sm table-striped">
        <thead>
            <tr>
                <th class="fit pl-1 pr-5">
                    @Html.DisplayNameFor(model => model.LastNameAndName)
                </th>
                <th class="fit pl-1 pr-5">
                    @Html.DisplayNameFor(model => model.FullAdress)
                </th>
                <th class="fit pl-1 pr-5">
                    @Html.DisplayNameFor(model => model.IdentityNumber)
                </th>
                <th>
                    Uzavřené pojistky
                </th>
                <th class="fit"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="align-middle fit pl-1 pr-5">
                        <a asp-action="Details" asp-route-id="@item.ID">@Html.DisplayFor(modelItem => item.LastNameAndName)</a>
                    </td>
                    <td class="align-middle fit pl-1 pr-5">
                        @Html.DisplayFor(modelItem => item.FullAdress)
                    </td>
                    <td class="align-middle fit pl-1 pr-5">
                        @Html.DisplayFor(modelItem => item.IdentityNumber)
                    </td>
                    <td class="align-middle">
                        @item.InsuranceInsureds.Count()
                    </td>
                    <td class="align-middle fit">
                        <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-warning">Editovat</a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Odstranit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-light-warning text-center h6" role="alert">
        Zatím nemáte v databázi žádného pojištěnce
    </div>
}